version: '3'
services:
    nginx:
        build: 
            context: ./build/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - appnet
    node1:
        build: 
            context: .
            dockerfile: ./build/node/Dockerfile
        ports:
            - "3000"
        networks:
            - appnet
    node2:
        build: 
            context: .
            dockerfile: ./build/node/Dockerfile
        links:
            - postgres
        ports:
            - "3000"
        networks:
            - appnet
    node3:
        build: 
            context: .
            dockerfile: ./build/node/Dockerfile
        links:
            - postgres
        ports:
            - "3000"
        networks:
            - appnet
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}
        networks:
            - appnet
networks:
    appnet:
        driver: bridge