nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./build/node
    links:
        - postgres
    ports:
        - "3001"
node2:
    build: ./build/node
    links:
        - postgres
    ports:
        - "3002"
node3:
    build: ./build/node
    links:
        - postgres
    ports:
        - "3003"
postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
        - "5432"